/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package down;

import com.google.gson.Gson;

import down.dto.PostDto;
import down.service.PostService;
import down.util.Fetch;

public class App {

    public static void main(String[] args) {
        // PostService postService = new PostService();
        // postService.findAll();
    }
}
